image: docker:git

services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  REGISTRY: registry.gitlab.com/

before_script:
  - apk add --no-cache make
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - make build push REGISTRY=$REGISTRY VERSION=$CI_BUILD_REF_NAME

spec:feature:mongo:
  stage: test
  before_script:
    - make up
  after_script:
    - make down
  script:
    - make test-mongo REGISTRY=$REGISTRY VERSION=$CI_BUILD_REF_NAME

spec:feature:elastic:
  stage: test
  before_script:
    - make up
  after_script:
    - make down
  script:
    - make test-elastic LINK_FLAGS= REGISTRY=$REGISTRY VERSION=$CI_BUILD_REF_NAME

release:image:
  stage: release
  script:
    - make pull tag REGISTRY=$REGISTRY VERSION=$CI_BUILD_REF_NAME
    - make push $REGISTRY=$REGISTRY
  only:
    - master

