stages:
  - test
  - release

image: node:5

before_script:
  - apt-get update -qy
  - apt-get install -y imagemagick
  - mkdir -p /var/opt/app/storage/upload
  - npm install --unsafe-perm

variables:
  APP_SEARCH_ENGINE_URI: "elasticsearch://elasticsearch:9200/keeper"
  APP_REDIS_URI: "redis://redis:6379/1"
  APP_ADMIN: "system"
  APP_STORAGE_LOCAL_DIR: "/var/opt/app/storage"

spec:feature:mongo:
  stage: test
  services:
    - mongo:latest
    - elasticsearch:latest
    - redis:latest
  script:
    - APP_DATABASE_URI="mongodb://mongo/keeper" npm test

spec:feature:elastic:
  stage: test
  services:
    - elasticsearch:latest
    - redis:latest
  script:
    - APP_DATABASE_URI="elasticsearch://elasticsearch:9200/keeper" npm test

release:image:
  stage: release
  image: docker:git
  services:
    - docker:dind
  before_script:
    - apk add --no-cache make
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  script:
    - make build push REGISTRY=registry.gitlab.com/
  only:
    - master

