image: docker:git

services:
  - docker:dind
  - mongo:latest
  - elasticsearch:latest
  - redis:latest

stages:
  - build
  - test
  - release

variables:
  REGISTRY: registry.gitlab.com/

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - make build push REGISTRY=$REGISTRY $VERSION=$CI_BUILD_REF_NAME

spec:feature:mongo:
  stage: test
  script:
    - make test-mongo REGISTRY=$REGISTRY $VERSION=$CI_BUILD_REF_NAME

spec:feature:elastic:
  stage: test
  script:
    - make test-elastic REGISTRY=$REGISTRY $VERSION=$CI_BUILD_REF_NAME

release:image:
  stage: release
  script:
    - make pull tag REGISTRY=$REGISTRY $VERSION=$CI_BUILD_REF_NAME
    - make push $REGISTRY=$REGISTRY
  only:
    - master

