sudo: false

language: node_js

node_js:
  - "6"

services:
  - mongodb
  - elasticsearch
  - redis

env:
  - APP_DATABASE_URI="mongodb://mongodb/keeper"
  - APP_SEARCH_ENGINE_URI="elasticsearch://elasticsearch:9200/keeper"
  - APP_REDIS_URI="redis://redis:6379/1"
  - APP_ADMIN="system"
  - APP_STORAGE_LOCAL_DIR="/var/opt/app/storage"

addons:
  apt:
    packages:
      - imagemagick

before_script:
  - mkdir -p /var/opt/app/storage/upload
