sudo: false

language: node_js

node_js:
  - "6"

services:
  - mongodb
  - elasticsearch
  - redis

env:
  global:
    - APP_ALLOW_AUTO_CREATE_USERS=true
    - APP_ALLOW_REMOVE_USERS=true
    - APP_TOKEN_SECRET="xyKFaqKHLG"
    - APP_DOWNLOADER="default"
    - APP_SEARCH_ENGINE_URI="elasticsearch://localhost:9200/keeper"
    - APP_REDIS_URI="redis://localhost:6379/1"
    - APP_ADMIN="system"
    - APP_STORAGE_LOCAL_DIR="/tmp/keeper/storage"
  matrix:
    - APP_DATABASE_URI="mongodb://localhost/keeper"
    - APP_DATABASE_URI="elasticsearch://localhost:9200/keeper"

addons:
  apt:
    packages:
      - imagemagick

before_script:
  - mkdir -p /tmp/keeper/storage
